[project]
name = "every-phonenumber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "peewee>=3.18.1",
    "phonenumbers>=9.0.7",
    "python-fasthtml>=0.12.36",
]
